In [1]:
#Question 1 
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [2]:
#Question 2
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [4]:
import numpy as np
l2_dist(np.reshape(a, (20*20)), np.reshape(b, (20*20, 1)))

NameError: name 'a' is not defined

In [5]:
#Question 3
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [8]:
a3.shape == a4.shape


False

In [9]:
a1.shape == a2.shape

False

In [10]:
a5.shape == a1.shape

True

In [11]:
a4.ndim() == 1

TypeError: 'int' object is not callable

In [12]:
#Question 4
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [23]:
#Question 5
import numpy as np 
test_array = np.ones((6,6))
test_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
r = test_array[2:4,2:4]
r

array([[1., 1.],
       [1., 1.]])

In [13]:
#Question 6
import re 
s = 'ACBCAC'

In [14]:
re.findall('[^A]C',s)

['BC']

In [15]:
re.findall('AC',s)

['AC', 'AC']

In [16]:
re.findall('^AC',s)

['AC']

In [17]:
re.findall('^[AC]',s)

['A']

In [19]:
#Question 7
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

5


In [20]:
#Question 10
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = \(.\)
print(len(re.findall(pattern,text)))

SyntaxError: unexpected character after line continuation character (<ipython-input-20-e1910606cbc1>, line 9)

In [32]:
#Question 9
sentence = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'

import re
#pattern = '(?<=https:\/\/)([A-Za-z0-9.]*)'
#pattern = '(?<=https:\/\/)([A-Za-z0-9]*)'
pattern = '(?<=[https]:\/\/)([A-Za-z0-9.]*)'
#pattern = '(?<=https:\/\/)([.]*)'
print(re.findall(pattern,sentence))


['']


In [35]:
#Question 10
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4
